services:
  mc:
    image: itzg/minecraft-server
    env_file:
      - .env
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./data/scripts:/scripts
    container_name: minecraft-server